### ISSUE TITLE
Menu doesn't work if <li> tag has additional classes

### ISSUE THREAD

**Issue by umarfarukm** [ma-5/ma5-mobile-menu#1]
We really liked this plugin and integreated in our website as wordpress editable :+1: 

But when the menu come from wordpress it adds few additional classes which cant be removed. That case the menu doesn't go to sub-menu panels. Please help for this issue.

How do i make it work even the < li > tags does have any number of classes.

**Comment by ma-5** [comment]
Thanks for info :) It's true. Menu not ready for other classes. Probably Wordpress classes should be arranged after classes MA5. I'm not sure Alternative you can transfer all MA5 class to data-class in javascript and rewrite all css from .ma5-... to  [data-class='ma5-...']

**Comment by ma-5** [comment]
Fixed, structure menu changed, i hope it's will work

**Comment by umarfarukm** [comment]
Thanks a lot :+1:

**Comment by Namennaj** [comment]
@umarfarukm Did you get it to work with Wordpress?  Are you willing to share the code? Thx

**Comment by ma-5** [comment]
This code can be used for Wordpress but it's needs implement.

**Comment by Namennaj** [comment]
@ma-5 Thanks for the info.  I will give it a go.
