### ISSUE TITLE
ajax problem

### ISSUE THREAD

**Issue by PabloManuel78** [ma-5/ma5-mobile-menu#3]
If I load the button via AJAX, the menu does not work:

`			
			<a href="#" class="navbar-text pull-left ma5-toggle-menu">
				<i class="fa fa-bars <?=$tamano?> fa-fw stilo_fa"></i>
				cn_menu
			</a>
`
I had to change this line
`$('.ma5-toggle-menu').on('click touch', function () {`
for this
`$(document.body).on( "click touch", ".ma5-toggle-menu", function() {`

**Comment by ma-5** [comment]
Thx for info! 👍
