### ISSUE TITLE
Not working in any iPhone Safari browser

### ISSUE THREAD

**Issue by ravismakwana** [ma-5/ma5-mobile-menu#8]
Hello 
This js is not working in iPhone devices like 7,8,10,11
Is there any idea to fix it?

Thank you 
Ravi

**Comment by ma-5** [comment]
I'm sure js works. I tested  it at iOS 7, 8, 9, 10, 11, 12, 13.

**Comment by ravismakwana** [comment]
I mean the issue is when I click on >> arrow for the submenu slide the entire menu closes.
http://simpwelldental.wpengine.com/
Please open this site on your iPhone device.
I hope you will get a solution for this.
Thank you 
Ravi

**Comment by ma-5** [comment]
I'm sorry but I don't know why it doesn't work on this site. I suggest checking with disable other JS and CSS
